# Generated by Django 3.2.10 on 2021-12-27 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(error_messages={'blank': 'ThisFieldCannotBeBlank'}, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(error_messages={'blank': 'ThisFieldCannotBeBlank'}, max_length=150, verbose_name='last name'),
        ),
    ]
