# Generated by Django 3.2.9 on 2021-12-22 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, error_messages={'blank': 'ThisFieldCannotBeBlank', 'unique': 'LabelWithThisNameAlreadyExist'}, help_text='HelpLabelFieldText', max_length=100, unique=True, verbose_name='LabelName')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Label',
                'verbose_name_plural': 'Labels',
                'ordering': ['name'],
            },
        ),
    ]
